new mac setup instructions
pulibrary/pul-it-handbook pull request #131
Opened 2022-08-26 19:32 UTC by Twade968

2022-08-26 19:45 UTC, bess requested changes
@Twade968 Please make the changes we talked about it, indicated in this PR. Thank you! 🚀

2022-08-26 19:45 UTC, bess commented on services/new_mac_setup.md
> +When you get a new mac here are some helpful guides to setting it up for software development in RDSS.
Remove reference to RDSS, since we're putting this into the general ITIMS handbook.

2022-08-26 19:45 UTC, bess commented on services/new_mac_setup.md
> +
Please add numbered headings to the different sections.

For example:
## 1. Setting up your unix prompt

2022-08-26 19:45 UTC, bess commented on services/new_mac_setup.md
> +We use zsh as a unix prompt. The last two setup steps(8,9) are not necessary for mac setup but will add more custimization options if you feel the need to install.
typo: customization

2022-08-26 19:45 UTC, bess commented on services/new_mac_setup.md
> +https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjJ8fzNxtr5AhXokmoFHU2CC5YQFnoECAUQAQ&url=https%3A%2F%2Fdocs.github.com%2Fen%2Fauthentication%2Fconnecting-to-g
Please link to a specific guide, not a list of google results 

Please include an indication of how someone will know that this is done correctly. For the zsh prompt, include a screen shot of YOUR correctly configured zsh prompt. For the ssh key, include a screen shot of a webpage with your public keys on it. (e.g., https://github.com/bess.keys)

2022-08-26 19:45 UTC, bess commented on services/new_mac_setup.md
> +New fellows may also want to rename the computer name,hostname and local hostname on your Mac machine. Below is the link to help rename.
Make it clear that "computer name, hostname, and local hostname" should all be the same. Again, provide a screen shot of yours, when it is set up correctly. 

Goal: `username@my_meaningful_computer_name`

2022-08-26 19:45 UTC, bess commented on services/new_mac_setup.md
> +go to the pdc_describe github page and checkout the projects dependencies and the local development setup information to become aware of the specific software plugins you will need to work on the pro
Remove reference to PDC describe

Add a list of applications to install with homebrew.

```
brew install gpg 
brew install postgres
brew install --cask lando
brew install asdf
```

Then, add asdf plugins.

2022-08-26 19:45 UTC, bess commented on services/new_mac_setup.md
> +Create a specific project profile in iterm2
Leave this part out for now.

2022-08-26 19:48 UTC, bess commented
Also add a section to configure git:

```
git config --global user.name "Your Name"
git config --global user.email "your_princeton_email"
git config --global core.pager bat
```

2022-11-15 21:01 UTC, leefaisonr commented on services/new_mac_setup.md
> +
Can this be inserted here?: 
services/images/change_hostname.png

2022-11-15 21:01 UTC, leefaisonr commented on services/new_mac_setup.md
> +
Can this be inserted here?:
services/images/github_jumpcloud_rename.png

2022-11-15 21:20 UTC, leefaisonr commented on services/new_mac_setup.md
> +brew install postgres
May need to run command:
```
brew install check_postgres
```

2022-11-15 21:20 UTC, leefaisonr commented on services/new_mac_setup.md
> +Trouble shooting:
Was there more information that needed to be added here?

2022-11-15 21:26 UTC, leefaisonr requested changes
Minor tweaks may be needed, overall this looks great and is easy to follow.

2022-11-18 16:05 UTC, merged