Adding static sites page
pulibrary/pul-it-handbook pull request #168
Opened 2023-05-15 14:52 UTC by escowles

Add a page for static sites, with brief pros/cons of each approach and links to each site

2023-05-15 16:07 UTC, kevinreiss requested changes
If you add the two I suggested. I think will cover all the "named" sites/exhibits we've archived in this fashion.

2023-05-15 16:07 UTC, kevinreiss commented on services/static_sites.md
> +* [Versailles Exhibit](https://github.com/pulibrary/versailles_exhibit_archive)
Add https://github.com/pulibrary/james_lyon_exhibit_archive and https://github.com/pulibrary/njmaps_exhibit_archive. These are jekyll sites.

2023-08-02 17:53 UTC, carolyncole approved these changes

2023-08-02 18:01 UTC, kevinreiss approved these changes

2023-08-02 18:01 UTC, merged