Create a document for roles
pulibrary/pul-it-handbook pull request #218
Opened 2023-09-27 18:14 UTC by carolyncole

2023-09-27 18:52 UTC, hackartisan requested changes
Thank you for this! One suggestion

2023-09-27 18:52 UTC, hackartisan commented on student-software-developers/administration-handbook/roles.md
> +  * Schedules Monthly Checkin
```suggestion
  * Schedules and Moderates Monthly Checkin 
```

2023-09-27 19:03 UTC, carolyncole commented
@hackartisan Great suggestion!  I merged it.

2023-09-28 13:20 UTC, hackartisan approved these changes

2023-09-28 13:21 UTC, merged