Add resume selection documentation for student hiring
pulibrary/pul-it-handbook pull request #241
Opened 2023-12-13 14:00 UTC by carolyncole

2023-12-13 14:11 UTC, carolyncole commented on student-software-developers/administration-handbook/resume-selection.md
> +   1. Creates and maintains a spreadheet that has the netid, a link to the content and a slot for two reviewers
```suggestion
   1. Creates and maintains a spreadsheet that has the netid, a link to the content and a slot for two reviewers  [see template](https://docs.google.com/spreadsheets/d/1rw_kw7psuiWlvJtjbfwyXjWxPsyfNCqSIWafj4Gm5YE/edit#gid=0) 
```

2023-12-13 14:41 UTC, hackartisan requested changes
This looks great and I think it reflects what we discussed. I wonder how it should interact with the info on https://github.com/pulibrary/pul-it-handbook/blob/main/student-software-developers/administration-handbook/roles.md. Maybe the roles should be moved there and we add a reference from this page? 

I also think it would be good to add links to this page from the January and February pages, since it's relevant to some of the stuff on those.

2023-12-18 13:52 UTC, carolyncole commented
@hackartisan since that role page is just a list it did not make much sense to change it, but I did link those role to the information in the more detailed page about resume selection.

Can you give me more information on what you want in the January February pages?

2024-01-04 15:54 UTC, hackartisan approved these changes
I feel good about this! I think it would be nice for @christinach to look over and ensure it is clear; I'm going to add a reviewer request.

2024-01-05 01:21 UTC, christinach approved these changes
Thank you it looks great!

2024-01-05 01:21 UTC, merged